"use client";

/**
 * OpsProvider — shared OPS session state
 *
 * Follows the same createContext + useReducer + custom-hook pattern as
 * OrgProvider and UIProvider. Lives at the shell layout level so state
 * persists across all OPS sub-page navigations without resetting.
 *
 * State initialises from mock data (Phase 1–2).
 * Phase 3 migration path: swap initialisation for an async fetch, or
 * replace the reducer dispatch calls with React Query mutations — no
 * page-component changes required.
 *
 * Responsibilities:
 *   - requests + work orders in one atomic state
 *   - request approval / assignment (with CRU worker linkage)
 *   - request → work order orchestration (auto-create on assign)
 *   - work order status transitions
 *
 * NOT responsible for:
 *   - CRU data fetching (stays in src/lib/integrations/cru.ts)
 *   - pour schedule (read-only CRU consumption, no owned state)
 *   - persistence (for now; designed to be replaced cleanly)
 */

import React, { createContext, useContext, useReducer } from "react";
import { MOCK_WORK_ORDERS, MOCK_REQUESTS } from "@/lib/ops/mock-data";
import type {
  WorkOrder,  WorkOrderStatus,
  Request as OpsRequest, RequestStatus,
} from "@/lib/ops/types";

// ── Transition rules ──────────────────────────────────────────────────────────
// Duplicated from service.ts intentionally: the provider is the UI state
// authority; service.ts is the API/data-layer authority. They share the same
// business rules but are independent modules.

const WORK_ORDER_TRANSITIONS: Record<WorkOrderStatus, WorkOrderStatus[]> = {
  open:          ["in_progress"],
  in_progress:   ["waiting_parts", "complete"],
  waiting_parts: ["in_progress"],
  complete:      [],
};

const REQUEST_TRANSITIONS: Record<RequestStatus, RequestStatus[]> = {
  pending:  ["approved"],
  approved: ["assigned"],
  assigned: [],
};

// ── State + action types ──────────────────────────────────────────────────────

interface OpsState {
  workOrders: WorkOrder[];
  requests:   OpsRequest[];
}

type WorkerInput = { id: string; label: string; role?: string };

type OpsAction =
  | { type: "APPROVE_REQUEST";   id: string }
  | {
      type:           "ASSIGN_REQUEST";
      id:             string;
      worker?:        WorkerInput;
      /** UUID pre-generated by the dispatcher — keeps the reducer pure */
      newWorkOrderId: string;
      createdAt:      string;
    }
  | { type: "UPDATE_WO_STATUS";  id: string; status: WorkOrderStatus }
  | { type: "CREATE_REQUEST";    request: OpsRequest };

// ── Reducer (pure — no side-effects, no randomness) ───────────────────────────

function opsReducer(state: OpsState, action: OpsAction): OpsState {
  switch (action.type) {

    case "APPROVE_REQUEST": {
      const req = state.requests.find((r) => r.id === action.id);
      if (!req || !REQUEST_TRANSITIONS[req.status].includes("approved")) return state;
      return {
        ...state,
        requests: state.requests.map((r) =>
          r.id === action.id ? { ...r, status: "approved" } : r,
        ),
      };
    }

    case "ASSIGN_REQUEST": {
      const req = state.requests.find((r) => r.id === action.id);
      if (!req || !REQUEST_TRANSITIONS[req.status].includes("assigned")) return state;

      const { worker, newWorkOrderId, createdAt } = action;

      const updatedReq: OpsRequest = {
        ...req,
        status:          "assigned",
        assignedToId:    worker?.id,
        assignedToLabel: worker?.label ?? "TBD",
        assignedToRole:  worker?.role,
      };

      // Orchestration: auto-create work order from assigned request.
      // sourceModule: "cru" when a real CRU worker is attached.
      const newWorkOrder: WorkOrder = {
        id:              newWorkOrderId,
        createdAt,
        title:           `Dispatch: ${req.type.replace("_", " ")} — ${req.jobsite}`,
        jobsite:         req.jobsite,
        assignedToLabel: worker?.label ?? "TBD",
        assignedToId:    worker?.id,
        assignedToRole:  worker?.role,
        status:          "open",
        priority:        "medium",
        sourceType:      "request",
        sourceId:        req.id,
        sourceModule:    worker?.id ? "cru" : "ops",
      };

      return {
        requests:   state.requests.map((r) => r.id === action.id ? updatedReq : r),
        workOrders: [...state.workOrders, newWorkOrder],
      };
    }

    case "CREATE_REQUEST": {
      return {
        ...state,
        requests: [...state.requests, action.request],
      };
    }

    case "UPDATE_WO_STATUS": {
      const wo = state.workOrders.find((w) => w.id === action.id);
      if (!wo || !WORK_ORDER_TRANSITIONS[wo.status].includes(action.status)) return state;
      return {
        ...state,
        workOrders: state.workOrders.map((w) =>
          w.id === action.id ? { ...w, status: action.status } : w,
        ),
      };
    }

    default:
      return state;
  }
}

const INITIAL_STATE: OpsState = {
  workOrders: [...MOCK_WORK_ORDERS],
  requests:   [...MOCK_REQUESTS],
};

// ── Context ───────────────────────────────────────────────────────────────────

interface OpsContextValue {
  workOrders:            WorkOrder[];
  requests:              OpsRequest[];
  approveRequest:        (id: string) => void;
  assignRequest:         (id: string, worker?: WorkerInput) => void;
  updateWorkOrderStatus: (id: string, status: WorkOrderStatus) => void;
  createRequest:         (data: Omit<OpsRequest, "id">) => void;
}

const OpsContext = createContext<OpsContextValue | null>(null);

// ── Provider ──────────────────────────────────────────────────────────────────

export function OpsProvider({ children }: { children: React.ReactNode }) {
  const [state, dispatch] = useReducer(opsReducer, INITIAL_STATE);

  function approveRequest(id: string): void {
    dispatch({ type: "APPROVE_REQUEST", id });
  }

  function assignRequest(id: string, worker?: WorkerInput): void {
    dispatch({
      type:           "ASSIGN_REQUEST",
      id,
      worker,
      // Pre-generate non-deterministic values so the reducer stays pure
      newWorkOrderId: crypto.randomUUID(),
      createdAt:      new Date().toISOString(),
    });
  }

  function updateWorkOrderStatus(id: string, status: WorkOrderStatus): void {
    dispatch({ type: "UPDATE_WO_STATUS", id, status });
  }

  function createRequest(data: Omit<OpsRequest, "id">): void {
    dispatch({ type: "CREATE_REQUEST", request: { ...data, id: crypto.randomUUID() } });
  }

  return (
    <OpsContext.Provider
      value={{
        workOrders: state.workOrders,
        requests:   state.requests,
        approveRequest,
        assignRequest,
        updateWorkOrderStatus,
        createRequest,
      }}
    >
      {children}
    </OpsContext.Provider>
  );
}

// ── Hook ──────────────────────────────────────────────────────────────────────

export function useOps(): OpsContextValue {
  const ctx = useContext(OpsContext);
  if (!ctx) throw new Error("useOps must be used within OpsProvider");
  return ctx;
}
